name: Setup Build Environment
description: Setup Swift
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          .build
        key: ${{ runner.os }}-build-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Git settings
      shell: bash
      run: |
        # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Show Swift version
      shell: bash
      run: |
        swift --version
