name: check-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 */3 * *" # Every 3 days at 8 AM

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            .build
          key: ${{ runner.os }}-build-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Clone AppStoreConnectKit
        run: |
          git clone https://x-access-token:${{ steps.generate.outputs.token }}@github.com/swiftty/AppStoreConnectKit.git
          cd AppStoreConnectKit/Sources/
          rm -rf AppStoreConnectKit
          mkdir AppStoreConnectKit
          cd ../..
          # Copy the template files to the AppStoreConnectKit
          cp Template/* AppStoreConnectKit/Sources/AppStoreConnectKit
      - name: Download openapi spec
        run: |
          mkdir tmp
          cd tmp
          curl "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip" -o app-store-connect-openapi-specification.zip
          unzip app-store-connect-openapi-specification.zip
          mv *.json openapi.oas.json
          cd ..
      - run: |
          swift build -c release
          ./.build/release/appstoreconnectgen --open-api-path tmp/openapi.oas.json --output AppStoreConnectKit/Sources/AppStoreConnectKit/autogenerated
      - name: Commit changes
        id: commit_changes
        run: |
          cd AppStoreConnectKit

          # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b update-generated-code
          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            echo "Changes detected"
            git commit -m "Update generated code"

            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Push branch
        if: steps.commit_changes.outputs.changed == 'true'
        id: push_branch
        run: |
          cd AppStoreConnectKit

          if git ls-remote --exit-code origin "refs/heads/update-generated-code"; then
            git push origin update-generated-code -f
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            git push origin update-generated-code
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create pull request
        if: steps.commit_changes.outputs.changed == 'true' && steps.push_branch.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          cd AppStoreConnectKit

          gh pr create \
            --title "Update generated code" \
            --body "This PR updates the generated code from the latest OpenAPI specification." \
            --base main \
            --head update-generated-code
