name: check-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 */3 * *" # Every 3 days at 8 AM

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .build
          key: ${{ runner.os }}-build-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: clone AppStoreConnectKit
        run: |
          git clone https://${{ steps.generate.outputs.token }}@github.com/swiftty/AppStoreConnectKit.git
          cd AppStoreConnectKit/Sources/
          rm -rf AppStoreConnectKit
          mkdir AppStoreConnectKit
          cd ..
          # Copy the template files to the AppStoreConnectKit
          cp Template/* AppStoreConnectKit/Sources/AppStoreConnectKit
      - name: git settings
        run: |
          # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: download openapi spec
        run: |
          mkdir tmp
          cd tmp
          curl "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip" -o app-store-connect-openapi-specification.zip
          unzip app-store-connect-openapi-specification.zip
          mv *.json openapi.oas.json
          cd ..
      - run: |
          swift build -c release
          ./.build/release/appstoreconnectgen -h
          ./.build/release/appstoreconnectgen --open-api-path tmp/openapi.oas.json --output AppStoreConnectKit/Sources/AppStoreConnectKit/autogenerated
      - name: commit changes
        id: commit_changes
        run: |
          cd AppStoreConnectKit
          if git diff --cached --quiet; then
            echo "No changes"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            git checkout -b update-generated-code
            git add .
            git commit -m "Update generated code"
            git push origin update-generated-code

            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: create pull request
        if: steps.commit_changes.outputs.changed == 'true'
        run: |
          cd AppStoreConnectKit
          gh auth login --with-token ${{ steps.generate.outputs.token }}
          gh pr create \
            --title "Update generated code" \
            --body "This PR updates the generated code from the latest OpenAPI specification." \
            --base main \
            --head update-generated-code
