name: renovate-resolved

on:
  push:
    branches: ["renovate/**"]
    paths:
      - "Package.swift"

jobs:
  mac-os:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Update Package.resolved
        run: |
          swift package resolve
      - name: Commit Package.resolved
        run: |
          git add -u
          git commit -m "Update Package.resolved"
          git push origin HEAD
