name: test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  check-generated-code:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            .build
          key: ${{ runner.os }}-build-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: |
          mkdir tmp
          cd tmp
          curl "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip" -o app-store-connect-openapi-specification.zip
          unzip app-store-connect-openapi-specification.zip
          mv *.json openapi.oas.json
          cd ..
      - run: |
          mkdir GeneratedProject
          cd GeneratedProject
          swift package init
          cd ..
      - run: |
          swift build -c release
          ./.build/release/appstoreconnectgen -h
          ./.build/release/appstoreconnectgen --open-api-path tmp/openapi.oas.json --output GeneratedProject/Sources/GeneratedProject/generated
      - run: |
          cp Template/* GeneratedProject/Sources/GeneratedProject
          cd GeneratedProject
          swift build
